services:
  resume_game:
    build:
      context: .
      dockerfile: Dockerfile
    image: resume-game-app
    container_name: resume-game-app
    restart: always
    environment:
      - DATABASE_URI=postgres://postgres:postgres@postgres_db:5432/resumegame?sslmode=disable
      - GRPC_SERVER=:3300
      - SERVER_CERT_FILE=/pkg/tlsconfig/cert/server/server.crt
      - SERVER_KEY_FILE=/pkg/tlsconfig/cert/server/server.key
      - SERVER_CA_FILE=/pkg/tlsconfig/cert/server/ca.crt
    ports:
      - "3300:3300"
    depends_on:
      - postgres_db

  # PostgreSQL database
  postgres_db:
    image: postgres:16-alpine3.20
    container_name: resume-game-postgres
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d resumegame" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=resumegame
    ports:
      - "5436:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: