// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: resumeUserV1.proto

package resumeUserV1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ResumeUserV1_SignUp_FullMethodName = "/resume_user_v1.ResumeUserV1/SignUp"
	ResumeUserV1_SignIn_FullMethodName = "/resume_user_v1.ResumeUserV1/SignIn"
)

// ResumeUserV1Client is the client API for ResumeUserV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResumeUserV1Client interface {
	SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*SignUpResponse, error)
	SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error)
}

type resumeUserV1Client struct {
	cc grpc.ClientConnInterface
}

func NewResumeUserV1Client(cc grpc.ClientConnInterface) ResumeUserV1Client {
	return &resumeUserV1Client{cc}
}

func (c *resumeUserV1Client) SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*SignUpResponse, error) {
	out := new(SignUpResponse)
	err := c.cc.Invoke(ctx, ResumeUserV1_SignUp_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resumeUserV1Client) SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error) {
	out := new(SignInResponse)
	err := c.cc.Invoke(ctx, ResumeUserV1_SignIn_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResumeUserV1Server is the server API for ResumeUserV1 service.
// All implementations must embed UnimplementedResumeUserV1Server
// for forward compatibility
type ResumeUserV1Server interface {
	SignUp(context.Context, *SignUpRequest) (*SignUpResponse, error)
	SignIn(context.Context, *SignInRequest) (*SignInResponse, error)
	mustEmbedUnimplementedResumeUserV1Server()
}

// UnimplementedResumeUserV1Server must be embedded to have forward compatible implementations.
type UnimplementedResumeUserV1Server struct {
}

func (UnimplementedResumeUserV1Server) SignUp(context.Context, *SignUpRequest) (*SignUpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUp not implemented")
}
func (UnimplementedResumeUserV1Server) SignIn(context.Context, *SignInRequest) (*SignInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignIn not implemented")
}
func (UnimplementedResumeUserV1Server) mustEmbedUnimplementedResumeUserV1Server() {}

// UnsafeResumeUserV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResumeUserV1Server will
// result in compilation errors.
type UnsafeResumeUserV1Server interface {
	mustEmbedUnimplementedResumeUserV1Server()
}

func RegisterResumeUserV1Server(s grpc.ServiceRegistrar, srv ResumeUserV1Server) {
	s.RegisterService(&ResumeUserV1_ServiceDesc, srv)
}

func _ResumeUserV1_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResumeUserV1Server).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResumeUserV1_SignUp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResumeUserV1Server).SignUp(ctx, req.(*SignUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResumeUserV1_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResumeUserV1Server).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResumeUserV1_SignIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResumeUserV1Server).SignIn(ctx, req.(*SignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ResumeUserV1_ServiceDesc is the grpc.ServiceDesc for ResumeUserV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResumeUserV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "resume_user_v1.ResumeUserV1",
	HandlerType: (*ResumeUserV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignUp",
			Handler:    _ResumeUserV1_SignUp_Handler,
		},
		{
			MethodName: "SignIn",
			Handler:    _ResumeUserV1_SignIn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resumeUserV1.proto",
}
